services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: proton_gluetun_container
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    ports: #make sure to include these from other apps to work #https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md
      - 6081:6881
      - 6081:6881/udp
      - 8888:8888/tcp
      #- 6011:6011 #qbittorrent
      - 3003:3000 #chromium
      #- 3001:3001 #chromium
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=cMghtf7LTTc02BAmpb4H+6KmyPK4ugrSU6pFxbb1VUA= 
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      #- SERVER_CITIES=New York #choose any available city
      - SERVER_HOSTNAMES:node-us-263.protonvpn.net
      - PORT_FORWARD_ONLY=ON
    volumes:
      #- gluetun:/var/lib/docker/volumes/gluetun
      - /var/lib/docker/volumes/gluetun-proton:/gluetun
    restart: unless-stopped

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium-test
    depends_on:
      - gluetun
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://whatismyipaddress.com/ #optional
      - WEBUI_PORT="192.168.0.208:3003:3000"
    volumes:
      - /home/atort88/docker/appdata/chromium-test:/config
      - "/media/plex_nas/browserdownloads:/config/Downloads:rw"
    network_mode: "container:proton_gluetun_container"
    #ports:
      #- "192.168.0.208:3000:3000"
      #- "192.168.0.208:3001:3001"
    shm_size: "1gb"
